version: "3"

services:
  lapin:
    build:
      context: .
      args:
        node_env: test
    image: lapin:test
    container_name: lapin
    command: yarn run test
    volumes:
      - ./src:/lapin/src
      - ./test:/lapin/test
      - ./spec:/lapin/spec
    environment:
      - AUTHLESS=1
      - COUCH=http://couch:5984
      - SHELL=/bin/sh
    tty: true
  couch:
    image: couchdb:1.7
    container_name: lapin_test_couch
    logging:
      driver: none
