version: "3"

services:
  lapin:
    build: .
    image: lapin:latest
    networks:
      access-platform:
        ipv4_address: 172.30.0.9
    command: yarn run start
networks:
  access-platform:
    external: true
